spring:
  application:
    name: recon

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 3s

    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    username: ${SPRING_ELASTICSEARCH_USERNAME}
    password: ${SPRING_ELASTICSEARCH_PASSWORD}


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ap-northeast-2


server:
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESSTOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESHTOKEN_EXPIRATION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender-number: ${COOLSMS_SENDER_NUMBER}

resilience4j:
  circuitbreaker:
    instances:
      redis:
        sliding-window-size: 10   #최근 10개 호출로 판단
        minimum-number-of-calls: 10   # 집계에 필요한 최소 호출 수
        failure-rate-threshold: 10   #실패 10% 이상시 오픈
        slow-call-rate-threshold: 10   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
        slow-call-duration-threshold: 500ms   # 500ms 이상 소요 시 실패로 간주
        wait-duration-in-open-state: 30s   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
        permitted-number-of-calls-in-half-open-state: 5   # HALF-OPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수
        ignore-exceptions: # 이 예외들은 실패로 처리하지 않음
          - com.project.recon.global.apiPayload.exception.GeneralException

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

